version: 2

aliases:
  - &working_directory
    ~/repo

  - &restore_cache
    keys:
    - v1-dependencies-{{ checksum "Gemfile.lock" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

  - &install
    name: Ruby dependencies
    command: bundle install

  - &npm_install
    name: npm dependencies
    command: npm install

  - &save_cache
    paths:
      - /usr/local/bundle
      - node_modules
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  - &tag_filters
    branches:
      ignore: /.*/
    tags:
      only: /^v?[0-9]+(\.[0-9]+)*/

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node

  working_directory: *working_directory

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            ruby --version
            node --version
            npm --version
            docker --version

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *install
      - run: *npm_install
      - save_cache: *save_cache

      - run:
          name: Build
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            npm run build
            npm run documentation-deploy-to-gh-pages

      # Persist the specified paths (workspace/echo-output) into the workspace
      # for use in downstream job. Must be an absolute path, or relative path
      # from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
      - persist_to_workspace:
          root: *working_directory
          paths:
            - dist
            - _gh_pages

# Workflows enable multiple jobs in parallel
workflows:
  version: 2

  deploy:
    jobs:
      - build
