version: 2

aliases:
  - &working_directory
    ~/repo

  - &restore_cache
    keys:
    - v3-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v3-dependencies-

  - &install
    name: Ruby dependencies
    command: bundle install

  - &npm_install
    name: npm dependencies
    command: npm install

  - &save_cache
    paths:
      - vendor/bundle
      - node_modules
    key: v3-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package.json" }}

  - &tag_filters
    branches:
      ignore: /.*/
    tags:
      only: /^v?[0-9]+(\.[0-9]+)*/

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node
      environment:
        BUNDLE_PATH: vendor/bundle
        JEKYLL_ENV: production

  working_directory: *working_directory

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            ruby --version
            bundle --version
            node --version
            npm --version
            docker --version

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *install
      - run: *npm_install
      - save_cache: *save_cache

      - run:
          name: Build
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            npm run build
            npm run documentation-deploy-to-gh-pages

      # Persist the specified paths (workspace/echo-output) into the workspace
      # for use in downstream job. Must be an absolute path, or relative path
      # from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
      - persist_to_workspace:
          root: *working_directory
          paths:
            - dist
            - _gh_pages

  release-github-assets:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .

      # Restore dependencies
      - restore_cache: *restore_cache
      - run: *npm_install

      - run:
          name: Add GitHub Release assets
          command: npm run upload-release-assets

# Workflows enable multiple jobs in parallel
workflows:
  version: 2

  deploy:
    jobs:
      - build:
          # Note: The build job must also have a filters tags section, as it is a transient dependency of the deploy job.
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/

      - release-github-assets:
          requires:
            - build
          filters: *tag_filters
